### ISSUE TITLE
Issue while debugging Air Mouse program

### ISSUE THREAD

**Issue by tcq720** [MandarGogate/AM-AIR-MOUSE#2]
Sir, I'm an electronics engineering student and I want to learn functioning of ARM microcontrollers. I saw your video of Air Mouse on youtube, and I'm trying to make something similar. I would be extremely grateful if you would help me out with this issue I'm facing right now.

**Comment by MandarGogate** [comment]
@tcq720 Please email me your query at contact [[AT}} mandargogate.com.
